//
// Created by nndng on 5/31/2022.
//

#ifndef STRINGMATCHINGALGORITHMS_STRINGMATCHINGONORDEREDALPHABETS_H
#define STRINGMATCHINGALGORITHMS_STRINGMATCHINGONORDEREDALPHABETS_H
#include <bits/stdc++.h>
std::vector<int> StringMatchingOnOrderedAlphabets(char *x, int m, char *y, int n);
#endif //STRINGMATCHINGALGORITHMS_STRINGMATCHINGONORDEREDALPHABETS_H
